42Box/front-end2.0

package.json
src/component/ScriptBoard.js
src/component/TextPreview.css
src/component/TextPreview.jsx
src/component/TextPreviewList.js
src/component/Util/Date.jsx
src/component/Util/Header.js
src/dummyPosts.js

미리보기를 더미 데이터를 넣어 볼 수 있도록 하였습니다.
추가로, node-modules 빌드 시간을 줄이고자 사용하지 않는 라이브러리(MUI, Chakra) 를 패키지에서 삭제하였습니다.

feat: ScriptBoard component

---

src/App.js
src/component/ScriptBoard.jsx
src/component/ScriptBoardContent.jsx
src/component/ScriptBoardSelect.jsx
src/component/TextPreviewList.jsx
src/component/Util/Button/GoBackButton.jsx
src/dummyPosts.js

- 게시글 미리보기를 누르면 게시글 콘텐츠 컴포넌트를 보여줍니다.
- 뒤로가기 버튼을 추가하였습니다.
- 글쓰기 게시판 URI를 "/boards/script-boards/new"로 변경하였습니다.

feat(ScriptBoard): click event for detail view

---

src/component/CommentNew.css
src/component/CommentNew.jsx
src/component/ScriptBoard.jsx
src/component/ScriptBoardContent.jsx
src/component/ScriptBoardNew.jsx
src/component/Util/Container.css

- 게시글 보기에 댓글 작성 textarea box를 추가하였습니다.
- <Container/> 에 max-width CSS 속성을 적용하여 내부 컴포넌트의 최대 크기에 제한을 주었습니다.

feat(Comment): comment textarea box

---

src/component/ScriptBoardNew.jsx

feat(ScriptBoardNew): add file input

---

src/component/CommentList.jsx
src/component/ScriptBoardContent.jsx

feat(ScriptBoardContent): add Container component

---

src/App.js
src/component/ScriptBoard.jsx
src/hook/useApi.js

test: test

---

package.json
src/App.js
src/component/ScriptBoard.jsx
src/hook/useApi.js

- axios 라이브러리를 추가하였습니다.
- useApi 훅을 구현했습니다.

feat: custom hook for api call

---

README.md
package.json
src/App.js
src/component/TextPreviewList.css
src/component/TextPreviewList.jsx
src/component/main/CommonButton.jsx
src/component/main/NotiBell.css
src/component/main/NotiBell.jsx
src/component/main/RandingPage.css
src/component/main/RandingPage.jsx
src/component/main/SideBar.jsx

readme는 왜 저렇게 됐지?
아무튼!
- 레이아웃만 짜봄
- 알림 사이드바 구현은 나중에

fix: RandingPage component close #15

---

src/App.js
src/atom/userState.js
src/component/Auth/Auth.jsx
src/hook/useApi.js
src/hook/useAuth.js

feat: login

---

src/component/ScriptBoard/ScriptBoardContent.css
src/component/ScriptBoard/ScriptBoardContent.jsx

- 화살표를 누르면 스크립트를 미리 볼 수 있습니다.
- css는 일단 생각하지 않고 어떤 기능인지 알게끔만 만들었습니다

feat(ScriptBoardContent): Toggle close #16

---

src/component/Main/LoginHeader.jsx
src/component/ScriptBoard/ScriptBoard.css
src/component/ScriptBoard/ScriptBoard.jsx
src/component/ScriptBoard/ScriptBoardContent.css
src/component/ScriptBoard/ScriptBoardContent.jsx

- 게시판 글들을 어떤 기준으로 정렬하여 볼지 선택할 수 있는 기능입니다.
- 로그인 안하면 마이페이지 안보이게 해놨습니다.

feat(ScriptBoard): sort option / filter

---

src/App.js
src/component/ScriptBoard/ScriptBoard.jsx
src/component/ServiceRegisterBoard/ServiceRegisterBoard.jsx
src/component/ServiceRegisterBoard/ServiceRegisterBoardContent.jsx
src/component/ServiceRegisterBoard/ServiceRegisterBoardSelect.jsx
src/component/TextPreview/TextPreviewList.jsx
src/component/main/RandingPage.jsx
src/dummyRegisterComments.js
src/dummyRegisters.js

* chore: add gitignore
* chore: add mandatory files
* wip: ui prototype
* chore: gitignore
* chore: remove package-lock.json
* chore: change name
* chore: update package.json
* chore: add package-lock.json
* Update README.md
* rename: rename files
* rename: roll-back
* build: add Chakra, MUI
* chore: initialize
* chore: change page title
* build: add icons, router-dom
* wip: Header, Buttons
* wip: TextPreview component
* build: remove MUI, Chakra
* feat(Date): Date component
* chore: dummy data for test
* fix(Header): fix className
* feat(ScriptBoard): ScriptBoard kkangtong
* feat: ScriptBoardNew component
* feat(component): Container
* feat(component): CommentList
* remove(component): remove Card
* feat(App): add temporary Route for detail view
* feat(component): ScriptBoardContent
* …

merge: ServiceRegisterBoard component (#74)

---

src/App.js
src/component/Util/NotFound.jsx
src/index.js

feat: page not found error page

---

src/hook/useOAuth.js

- 임의 쿠키 설정 코드를 삭제하였습니다. user-service에 날린 콜에 대한 응답으로 쿠키를 세팅하는게 아니라 OAuth 과정에서 백엔드가 Set-Cookie 해주기 때문입니다.

fix: remove stupid logic

---

src/component/ScriptBoard/ScriptBoardContent.jsx

feat: script download and reload

---

src/App.js
src/component/Main/LoginButton.jsx
src/component/Main/LoginHeader.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/hook/useOAuth.js

- 로그인과 아웃시 로컬 스토리지에 로그인 상태를 저장 혹은 삭제 합니다
- 새로고침 등으로 리랜더링될때마다 localStorage를 먼저 확인하고 recoilState를 업데이트 해줍니다. useEffect에 depth는 빈배열로 줘서 첫 랜더링시에만 업데이트가 실행되도록 했습니다.
- **진짜 로그인(Auth컴포넌트 호출)을 하면 배포 버전인 42box.kr로 리다이렉트 되어 테스트를 하지 못하는 이슈가 있어서.. 테스트를 위한 가짜 로그인 코드를 추가했습니다. 추후 주석을 처리했다가 안했다가 왔다 갔다 하면 됩니다.**

Feat: save login state in localstorage

---

src/component/Main/IconBoardPreview.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/hook/useOAuth.js

아직 컴포넌트화의 필요성을 못느껴서 필요한 곳에 함수만 만들었습니다.
1. 로그인시 유저 정보 전달 
2. 스크립트 파일 다운 시 절대경로 전달(다운로드를 위함)
3. 메인화면 아이콘 게시판에서 아이콘 클릭시 아이콘 정보 전달(아이콘 변경을 위함)

feat(Any): add function sending data to macos app #131

---

src/component/Main/IconBoardPreview.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/hook/useOAuth.js

아직 컴포넌트화의 필요성을 못느껴서 필요한 곳에 함수만 만들었습니다.
1. 로그인시 유저 정보 전달
2. 스크립트 파일 다운 시 절대경로 전달(다운로드를 위함)
3. 메인화면 아이콘 게시판에서 아이콘 클릭시 아이콘 정보 전달(아이콘 변경을 위함)
배포 실패해서 고치고 다시 올려요

Fix: erase unuse import

---

src/component/ScriptBoard/ScriptBoardNew.jsx
src/hook/useApi.js
src/hook/useScriptBoardNew.js
src/util/apiCall.js

- 스크립트게시판에 글을 작성할 수 있습니다.
- 제목, 내용 길이 제한을 일단 API에 맞추었습니다. 변경을 원하실 경우 추후에 상의해서 변경하면 될 것 같습니다.
- useApi 내부의 apiCall 함수를 분리하였습니다. POST 요청과 같은 경우에는 제출 버튼 클릭과 같은 이벤트 발생 시 핸들러 내부에서 호출되어야 하는데, useApi 와 같은 훅은 핸들러 외부에서만 호출될 수 있기 때문입니다.

feat: ScriptBoradNew api

---

src/component/ScriptBoard/ScriptBoardContent.jsx
src/hook/useOAuth.js
src/mocks/handlers.js

- .. async await를 붙이지 않아서, apiCall이 비동기로 돌아가는동안 참사

Feat scriptboardcontent api call

---

src/component/Main/IconBoardPreview.jsx
src/component/Main/LoginButton.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/mocks/fetchData.js
src/mocks/handlers.js
src/util/apiCall.js

- base URL을 api.42box.site 에서 api.42box.kr 로 변경하였습니다.

feat: change base url

---

src/component/Main/IconBoardPreview.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx

- 파일 저장 / 삭제 로직을 수정했습니다.
- 아이콘 보드 프리뷰의 axios put 요청 코드를 apiCall 함수로 수정했습니다

Fix: scaripboardcontent file save logic

---

src/component/TextPreview/TextPreview.jsx
src/component/TextPreview/TextPreviewList.jsx
src/component/Util/DateComponent.jsx

- 게시글의 설명이 길면 잘려서 표시됩니다.
- 날짜 표시 방법을 개선하였습니다.
- 현재로부터 한 시간 이내는 XX분 전
- 하루 이내는 XX : XX
- 그 이전은 년 : 월 : 일 의 형태로 표시됩니다.
- S3에서 받아온 프로필 이미지가 표시됩니다.

feat(ScriptBoard): detail improvement

---

src/component/TextPreview/TextPreview.jsx

fix: height, content preview

---

package.json
src/component/Comment/CommentNew.css
src/component/Comment/CommentNew.jsx
src/component/ScriptBoard/CommentPaging.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/component/Util/Header.jsx
src/mocks/handlers.js
src/util/errorHandling.js

- 파일 저장 / 실행 찌금 수정
- ui 수정
- 스크립트 미리보기 구현
- 댓글 페이지네이션 구현(근데! 댓글이 아예 없는 경우 404에러가 뜨는 점 양해 부탁. 그냥 닫기 버튼 누르면 됨)
해야할 것
- 스크립트 미리보기 디테일(에러뜨면 이상해짐, 요청을 너무 많이 보냄 등)
- 댓글 디테일
- 좋아요

feat: 스크립트 미리보기까지 + mac에 description말고 title 보내기

---

src/component/Main/LoginButton.jsx
src/component/Main/LoginHeader.jsx
src/component/TextPreview/TextPreview.jsx
src/component/TextPreview/TextPreviewList.jsx
src/theme.js

- 게시판 뷰 css 가 사파리 13 버전에서 깨지지 않고 나옵니다.
- 추가로, 로그인 버튼 높이 조정 및 호버 적용하였습니다.

fix: board preview, login button

---

src/component/ScriptBoard/ScriptBoard.jsx
src/component/Util/Button/FilterButton.jsx
src/component/Util/Button/SortButton.jsx
src/component/Util/Button/SortPopularButton.jsx
src/component/Util/FilterOptions.jsx
src/component/Util/SearchBar.jsx
src/component/Util/SearchFilterSort.jsx

feat(ScriptBoard): search title

---

src/component/ScriptBoard/ScriptBoard.jsx
src/component/Util/SearchBar.jsx
src/component/Util/SearchFilterSort.jsx
src/recoil/searchBarState.js

feat(ScriptBoard): sort new

---

src/component/ScriptBoard/ScriptBoardContent.jsx
src/mocks/handlers.js

- 비동기 처리 문제였나 싶습니다. 흑흑 일단 시도해보자

feat: await 추가해서 세팅 다 하고 mac에 보내기

---

src/api/useGetBoardInfo.js
src/component/ScriptBoard/ScriptBoard.jsx
src/component/Util/Pagenation.jsx

- 새로고침 시 페이지네이션이 초기화되던 문제를 URL에 쿼리스트링을 저장하는 식으로 해결했습니다.

fix: board pagenation initialization on reload

---

src/component/Util/SearchFilterSort.jsx

feat(ScriptBoard): sort popular

---

src/component/Main/LoginHeader.jsx

- 로그아웃 시 초기화 할 리코일 객체 멤버 추가(bigProfileImage)
- 로그아웃 시 지워지지 지지 않고 있던 localStorage의 userState 삭제

fix: logoutHandler

---

src/asset/next.svg
src/asset/nextInvalid.svg
src/asset/previous.svg
src/asset/previousInvalid.svg
src/component/MyPage/StatusMessage.jsx
src/component/ScriptBoard/ScriptBoard.jsx
src/component/Util/Button/PagenationButton.jsx
src/component/Util/NoPosts.jsx
src/component/Util/PageNumbers.jsx
src/component/Util/Pagenation.jsx
src/component/Util/SearchBar.jsx

- 페이지 번호 디자인을 완료하였습니다.
- 페이지 번호를 클릭하면 해당 페이지로 이동합니다.
- 검색 결과가 없을 경우 검색 결과가 없다는 메시지를 표시합니다.
- 더 이상 이동할 페이지가 없을 경우 이전/다음 페이지 버튼이 비활성화됩니다.

feat: pagenation design finish

---

src/App.js
src/asset/meatball-menu.svg
src/component/Comment/CommentList.jsx
src/component/Main/IconBoardPreview.jsx
src/component/ScriptBoard/BoardMain.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/component/ScriptBoard/ScriptBoardEdit.jsx
src/component/ScriptBoard/ScriptPreviewPop.jsx

그 외에, 
- 아이콘보드의 아이콘을 좀 더 깔끔하게 보이도록 노오력했습니다
- like와 댓글수 아이콘간 간격을 넓혔습니다.

feat: post edit, delete

---

src/component/IconBoard/IconBoard.jsx
src/component/IconBoard/IconGalleryView.jsx

feat: icon board content change

---

src/component/Main/IconBoardPreview.jsx
src/component/ScriptBoard/BoardMain.jsx
src/component/ScriptBoard/ScriptBoardContent.jsx
src/component/ScriptBoard/ScriptPreviewButtons.jsx
src/component/ScriptBoard/ScriptPreviewPop.jsx
src/component/ServiceBoard/ServiceBoardContent.jsx
src/component/Util/ScriptPreviewButtonArrow.jsx

- css 수정을 완료하였습니다.
- 달리는 여우 그래픽을 수정하였습니다.
- backend 와 macos에 아이콘 이름을 잘 넘겨줍니다.
- 스크립트 미리보기를 수정하였습니다.

fix: layout bug in safari 113
